name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
    - name: Download SL source
      run: |
        gh release -R mtoyoda/sl download -A tar.gz -O sl.tar.gz
        mkdir sl
        tar -xzf sl.tar.gz -C sl --strip-components 1
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Download PDCurses source
      run: |
        gh release -R wmcbrine/PDCurses download -A tar.gz -O PDCurses.tar.gz
        mkdir PDCurses
        tar -xzf PDCurses.tar.gz -C PDCurses --strip-components 1
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Build PDCurses
      working-directory: PDCurses\\wincon
      run: make
      env:
        PDCURSES_SRCDIR: ${{ github.workspace }}\\sl\\PDCurses
    - name: Rename library file
      working-directory: sl/PDCurses
      run: rename pdcurses.a libncurses.a
    - name: Apply a patch file to SL Makefile
      run: patch -u sl\\Makefile sl.patch
    - name: Build
      working-directory: sl
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sl
        path: ${{ github.workspace }}\\sl\\sl.exe
        if-no-files-found: error
        retention-days: 1
